In [1]:
!pip uninstall -y peft fastai timm torchvision torchaudio torch transformers accelerate datasets tf-keras


Found existing installation: peft 0.18.1
Uninstalling peft-0.18.1:
  Successfully uninstalled peft-0.18.1
Found existing installation: fastai 2.8.6
Uninstalling fastai-2.8.6:
  Successfully uninstalled fastai-2.8.6
Found existing installation: timm 1.0.24
Uninstalling timm-1.0.24:
  Successfully uninstalled timm-1.0.24
Found existing installation: torchvision 0.24.0+cu126
Uninstalling torchvision-0.24.0+cu126:
  Successfully uninstalled torchvision-0.24.0+cu126
Found existing installation: torchaudio 2.9.0+cu126
Uninstalling torchaudio-2.9.0+cu126:
  Successfully uninstalled torchaudio-2.9.0+cu126
Found existing installation: torch 2.9.0+cu126
Uninstalling torch-2.9.0+cu126:
  Successfully uninstalled torch-2.9.0+cu126
Found existing installation: transformers 4.57.6
Uninstalling transformers-4.57.6:
  Successfully uninstalled transformers-4.57.6
Found existing installation: accelerate 1.12.0
Uninstalling accelerate-1.12.0:
  Successfully uninstalled accelerate-1.12.0
Found existing in

In [3]:
!pip install transformers==4.36.2 datasets accelerate


  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
  Using cached datasets-4.5.0-py3-none-any.whl.metadata (19 kB)
  Using cached accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
  Using cached tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
  Using cached pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Using cached transformers-4.36.2-py3-none-any.whl (8.2 MB)
Using cached datasets-4.5.0-py3-none-any.whl (515 kB)
Using cached accelerate-1.12.0-py3-none-any.whl (380 kB)
Using cached pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
Using cached tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstall

In [2]:
!pip install torch==2.10.0



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.7/915.7 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 79.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 136.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 68.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 74.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 107.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 46.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.9/380.9 kB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 17.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 112.0 MB/s eta 0:00:00
ERROR: Operation cancelled by user
^C


In [26]:
!pip uninstall -y accelerate
!pip install accelerate==0.25.0



Found existing installation: accelerate 1.12.0
Uninstalling accelerate-1.12.0:
  Successfully uninstalled accelerate-1.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 9.6 MB/s eta 0:00:00


In [4]:
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())


Torch version: 2.10.0+cu128
CUDA available: True


In [1]:
from datasets import Dataset
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)

print("✅ Transformers import successful")


/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(


✅ Transformers import successful


In [23]:

import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score, f1_score, classification_report,confusion_matrix

**Load Your Train & Validation Data**

In [ ]:
train_df = pd.read_csv("../data/processed/train_baseline.csv")
val_df   = pd.read_csv("../data/processed/val_baseline.csv")

print(train_df.shape, val_df.shape)
train_df.head()


(42144, 2) (10537, 2)


text  label
0  trying make plan recently keep thing come unde...      1
1  want cut bad think right normally get urge pun...      2
2  lot people life friend family love one cannot ...      2
3                                              shiba      1
4  original original end end angry every hour fea...      0

**Basic Safety Checks**

In [7]:
# Drop missing values (just in case)
train_df = train_df.dropna(subset=["text", "label"])
val_df   = val_df.dropna(subset=["text", "label"])

# Ensure correct types
train_df["label"] = train_df["label"].astype(int)
val_df["label"]   = val_df["label"].astype(int)

print("Labels in train:", sorted(train_df["label"].unique()))
print("Labels in val:", sorted(val_df["label"].unique()))


Labels in train: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
Labels in val: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]


**Convert Pandas → HuggingFace Dataset**

In [8]:
train_dataset = Dataset.from_pandas(
    train_df[["text", "label"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[["text", "label"]],
    preserve_index=False
)


**Load Tokenizer**

In [9]:
tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


**Tokenization**

In [10]:
def tokenize_function(batch):
  return tokenizer(
      batch['text'],
      truncation=True,
      padding=False,
      max_length=128
  )

train_dataset=train_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

val_dataset=val_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)


Map:   0%|          | 0/42023 [00:00<?, ? examples/s]

Map:   0%|          | 0/10506 [00:00<?, ? examples/s]

**Data Collator (Dynamic Padding)**

In [11]:
data_collator=DataCollatorWithPadding(tokenizer=tokenizer)

**Load DistilBERT Model**

In [12]:
num_labels=train_df['label'].nunique()
print("Number of labels:", num_labels)

Number of labels: 7


In [13]:
model=DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased',
    num_labels=num_labels
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'pre_classifier.bias', 'classifier.weight', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


**Metrics Function (For Evaluation)**

In [14]:
def compute_metrics(eval_pred):
  logits, labels= eval_pred
  preds= np.argmax(logits, axis=1)

  return {
      "accuracy": accuracy_score(labels, preds),
      "f1_macro":f1_score(labels,preds, average='macro')
  }

**Training Arguments**

In [15]:
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,   # reduce to 8 if CPU is slow
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=200,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    report_to="none"
)


In [2]:
import accelerate
print(accelerate.__version__)

0.25.0


**Trainer Setup**

In [16]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)


**TRAIN THE MODEL**

In [17]:
trainer.train()

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


TrainOutput(global_step=7881, training_loss=0.5014485416187277, metrics={'train_runtime': 1562.7449, 'train_samples_per_second': 80.672, 'train_steps_per_second': 5.043, 'total_flos': 4083094913226318.0, 'train_loss': 0.5014485416187277, 'epoch': 3.0})

**Final Evaluation Report**

In [21]:
# Run prediction
preds_output = trainer.predict(val_dataset)

# True labels
y_true = preds_output.label_ids

# Predicted labels
y_pred = np.argmax(preds_output.predictions, axis=1)

print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       768
           1       0.93      0.94      0.93      3241
           2       0.75      0.74      0.74      3078
           3       0.67      0.69      0.68      2131
           4       0.67      0.66      0.66       517
           5       0.87      0.83      0.85       556
           6       0.75      0.72      0.73       215

    accuracy                           0.80     10506
   macro avg       0.78      0.77      0.78     10506
weighted avg       0.80      0.80      0.80     10506



In [24]:
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[ 656   10   39    1   29   21   12]
 [  18 3042   41   58   75    3    4]
 [  30   67 2275  640   28   22   16]
 [   7   81  570 1466    3    2    2]
 [  35   72   42    5  340   12   11]
 [  23    9   40    2   15  459    8]
 [   7    6   24    0   16    7  155]]


**Save Model**

In [25]:
trainer.save_model("./mental_health_distilbert")
tokenizer.save_pretrained("./mental_health_distilbert")


('./mental_health_distilbert/tokenizer_config.json',
 './mental_health_distilbert/special_tokens_map.json',
 './mental_health_distilbert/vocab.txt',
 './mental_health_distilbert/added_tokens.json',
 './mental_health_distilbert/tokenizer.json')

In [26]:
model.save_pretrained("/content/final_model")
tokenizer.save_pretrained("/content/final_model")


('/content/final_model/tokenizer_config.json',
 '/content/final_model/special_tokens_map.json',
 '/content/final_model/vocab.txt',
 '/content/final_model/added_tokens.json',
 '/content/final_model/tokenizer.json')

In [27]:
!zip -r final_model.zip /content/final_model


  adding: content/final_model/ (stored 0%)
  adding: content/final_model/tokenizer_config.json (deflated 76%)
  adding: content/final_model/config.json (deflated 53%)
  adding: content/final_model/vocab.txt (deflated 53%)
  adding: content/final_model/model.safetensors (deflated 8%)
  adding: content/final_model/tokenizer.json (deflated 71%)
  adding: content/final_model/special_tokens_map.json (deflated 42%)
